/*
 * Copyright 2010 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.drools.examples.helloworld
 
import org.ff4j.drools.FF4jDroolsRequest;

global org.ff4j.core.FeatureStore store

rule "f1_checkSampleThreshold"
    dialect "mvel"
     when
        $req : FF4jDroolsRequest( featureName == "f1", evaluated == false )
     then
        System.out.println("Evaluating F1 Strategy");
        System.out.println(store.getClass().getName());
        modify ($req) {
            evaluated = true,
        	toggled = true
        };
end
