#release configuration
#Tue Sep 29 19:17:20 CEST 2026
completedPhase=run-preparation-goals
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.dev.org.ff4j\:ff4j-aop=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-cli=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-config-properties=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-config-yaml=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-core=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-jmx=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-parent=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-security-shiro=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-security-spring=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-store-arangodb=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-store-archaius=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-store-aws-dynamodb=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-store-aws-ssm=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-store-cassandra=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-store-commonsconfig=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-store-consul=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-store-couchbase=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-store-couchdb=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-store-ehcache=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-store-elastic=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-store-gcp-datastore=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-store-hazelcast=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-store-hbase=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-store-ignite=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-store-jcache=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-store-mongodb=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-store-neo4j=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-store-redis=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-store-springjdbc=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-strategy-drools=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-test=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-utils-json=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-web=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-webapi=3.0.1-SNAPSHOT
project.dev.org.ff4j\:ff4j-webapi-client=3.0.1-SNAPSHOT
project.rel.org.ff4j\:ff4j-aop=3.0.0
project.rel.org.ff4j\:ff4j-cli=3.0.0
project.rel.org.ff4j\:ff4j-config-properties=3.0.0
project.rel.org.ff4j\:ff4j-config-yaml=3.0.0
project.rel.org.ff4j\:ff4j-core=3.0.0
project.rel.org.ff4j\:ff4j-jmx=3.0.0
project.rel.org.ff4j\:ff4j-parent=3.0.0
project.rel.org.ff4j\:ff4j-security-shiro=3.0.0
project.rel.org.ff4j\:ff4j-security-spring=3.0.0
project.rel.org.ff4j\:ff4j-store-arangodb=3.0.0
project.rel.org.ff4j\:ff4j-store-archaius=3.0.0
project.rel.org.ff4j\:ff4j-store-aws-dynamodb=3.0.0
project.rel.org.ff4j\:ff4j-store-aws-ssm=3.0.0
project.rel.org.ff4j\:ff4j-store-cassandra=3.0.0
project.rel.org.ff4j\:ff4j-store-commonsconfig=3.0.0
project.rel.org.ff4j\:ff4j-store-consul=3.0.0
project.rel.org.ff4j\:ff4j-store-couchbase=3.0.0
project.rel.org.ff4j\:ff4j-store-couchdb=3.0.0
project.rel.org.ff4j\:ff4j-store-ehcache=3.0.0
project.rel.org.ff4j\:ff4j-store-elastic=3.0.0
project.rel.org.ff4j\:ff4j-store-gcp-datastore=3.0.0
project.rel.org.ff4j\:ff4j-store-hazelcast=3.0.0
project.rel.org.ff4j\:ff4j-store-hbase=3.0.0
project.rel.org.ff4j\:ff4j-store-ignite=3.0.0
project.rel.org.ff4j\:ff4j-store-jcache=3.0.0
project.rel.org.ff4j\:ff4j-store-mongodb=3.0.0
project.rel.org.ff4j\:ff4j-store-neo4j=3.0.0
project.rel.org.ff4j\:ff4j-store-redis=3.0.0
project.rel.org.ff4j\:ff4j-store-springjdbc=3.0.0
project.rel.org.ff4j\:ff4j-strategy-drools=3.0.0
project.rel.org.ff4j\:ff4j-test=3.0.0
project.rel.org.ff4j\:ff4j-utils-json=3.0.0
project.rel.org.ff4j\:ff4j-web=3.0.0
project.rel.org.ff4j\:ff4j-webapi=3.0.0
project.rel.org.ff4j\:ff4j-webapi-client=3.0.0
project.scm.org.ff4j\:ff4j-parent.connection=scm\:git\:git@github.com\:ff4j/ff4j.git
project.scm.org.ff4j\:ff4j-parent.developerConnection=scm\:git\:git@github.com\:ff4j/ff4j.git
project.scm.org.ff4j\:ff4j-parent.tag=HEAD
project.scm.org.ff4j\:ff4j-parent.url=git@github.com\:ff4j/ff4j.git
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=true
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tag=3.0.0
scm.tagNameFormat=@{project.version}
scm.url=scm\:git\:git@github.com\:ff4j/ff4j.git
