CREATE TABLE FF4J_FEATURES (
  UID     		VARCHAR(50),
  ENABLE  		INTEGER NOT NULL,
  DESCRIPTION 	VARCHAR(255),
  STRATEGY		VARCHAR(255),
  EXPRESSION	VARCHAR(255),
  PRIMARY KEY(UID)
);

CREATE TABLE FF4J_ROLES (
  FEAT_UID     VARCHAR(50) REFERENCES FF4J_FEATURES(UID),
  ROLE_NAME    VARCHAR(50),
  PRIMARY KEY(FEAT_UID, ROLE_NAME)
);
