CREATE TABLE FF4J_FEATURES ( 
 FEAT_UID 		VARCHAR(100) NOT NULL,
 CREATED 		DATETIME NOT NULL,
 LASTMODIFIED 	DATETIME NOT NULL,
 OWNER 			VARCHAR(100),
 DESCRIPTION 	VARCHAR(255),
 ENABLE 		INTEGER NOT NULL,
 STRATCLASS 	VARCHAR(1000),
 STRATPARAM 	VARCHAR(1000),
 GROUPNAME 		VARCHAR(100),
 PRIMARY KEY (FEAT_UID)
);

CREATE TABLE FF4J_ROLES ( 
 FEAT_UID 	VARCHAR(100) NOT NULL,
 ROLE_NAME 	VARCHAR(100) NOT NULL,
 PRIMARY KEY (FEAT_UID,ROLE_NAME),
 FOREIGN KEY (FEAT_UID) REFERENCES FF4J_FEATURES(FEAT_UID)
);

CREATE TABLE FF4J_CUSTOM_PROPERTIES ( 
 PROPERTY_ID 	VARCHAR(100) NOT NULL,
 READONLY 		INTEGER NOT NULL,
 CREATED 		DATETIME NOT NULL,
 LASTMODIFIED 	DATETIME NOT NULL,
 OWNER 			VARCHAR(100),
 DESCRIPTION 	VARCHAR(255),
 CLAZZ 			VARCHAR(255) NOT NULL,
 CURRENTVALUE 	VARCHAR(255) NOT NULL,
 STRATCLASS 	VARCHAR(1000),
 STRATPARAM 	VARCHAR(1000),
 FIXEDVALUES 	VARCHAR(1000),
 FEAT_UID 		VARCHAR(100) NOT NULL,
 PRIMARY KEY (PROPERTY_ID,FEAT_UID),
 FOREIGN KEY (FEAT_UID) REFERENCES FF4J_FEATURES(FEAT_UID)
);

CREATE TABLE FF4J_PROPERTIES ( 
 PROPERTY_ID 	VARCHAR(100) NOT NULL,
 READONLY 		INTEGER NOT NULL,
 CREATED 		DATETIME NOT NULL,
 LASTMODIFIED 	DATETIME NOT NULL,
 OWNER 			VARCHAR(100),
 DESCRIPTION 	VARCHAR(255),
 CLAZZ 			VARCHAR(255) NOT NULL,
 CURRENTVALUE 	VARCHAR(255) NOT NULL,
 STRATCLASS 	VARCHAR(1000),
 STRATPARAM 	VARCHAR(1000),
 FIXEDVALUES 	VARCHAR(1000),
 PRIMARY KEY (PROPERTY_ID)
);

CREATE TABLE FF4J_AUDIT ( 
 UID 			VARCHAR(100) NOT NULL,
 CREATED 		DATETIME NOT NULL,
 LASTMODIFIED 	DATETIME NOT NULL,
 OWNER 			VARCHAR(100),
 DESCRIPTION 	VARCHAR(255),
 EVT_TIME 		TIMESTAMP NOT NULL,
 EVT_TYPE 		VARCHAR(30) NOT NULL,
 NAME 			VARCHAR(30) NOT NULL,
 ACTION 		VARCHAR(30) NOT NULL,
 HOSTNAME 		VARCHAR(100),
 SOURCE 		VARCHAR(100),
 DURATION 		INTEGER NOT NULL,
 EVT_VALUE 		VARCHAR(100) NOT NULL,
 EVT_KEYS 		VARCHAR(1000) NOT NULL,
 PRIMARY KEY (UID,EVT_TIME)
);

CREATE TABLE FF4J_METRICS ( 
 UID 			VARCHAR(100) NOT NULL,
 CREATED 		DATETIME NOT NULL,
 LASTMODIFIED 	DATETIME NOT NULL,
 OWNER 			VARCHAR(100),
 DESCRIPTION 	VARCHAR(255),
 EVT_TIME 		TIMESTAMP NOT NULL,
 EVT_TYPE 		VARCHAR(30) NOT NULL,
 NAME 			VARCHAR(30) NOT NULL,
 ACTION 		VARCHAR(30) NOT NULL,
 HOSTNAME 		VARCHAR(100),
 SOURCE 		VARCHAR(100),
 DURATION 		INTEGER NOT NULL,
 EVT_VALUE 		VARCHAR(100) NOT NULL,
 EVT_KEYS 		VARCHAR(1000) NOT NULL,
 PRIMARY KEY (UID,EVT_TIME)
);
