CREATE TABLE FF4J_FEATURE ( 
 UID 			VARCHAR(100) NOT NULL,
 CREATED 		DATETIME NOT NULL,
 LASTMODIFIED 	DATETIME NOT NULL,
 OWNER 			VARCHAR(100),
 DESCRIPTION 	VARCHAR(255),
 ENABLE 		INTEGER NOT NULL,
 GROUPNAME 		VARCHAR(100),
 PRIMARY KEY (UID)
);

CREATE TABLE FF4J_FEATURE_PROP ( 
 UID 			VARCHAR(100) NOT NULL,
 CLASSNAME 		VARCHAR(255) NOT NULL,
 VAL 			VARCHAR(255) NOT NULL,
 FIXEDVALUES 	VARCHAR(1000),
 FEAT_UID 		VARCHAR(100) NOT NULL,
 PRIMARY KEY (UID,FEAT_UID),
 FOREIGN KEY (FEAT_UID) REFERENCES FF4J_FEATURE(UID)
);

CREATE TABLE FF4J_FEATURE_PERM ( 
 FEATURE 		VARCHAR(100) NOT NULL,
 RIGHTS 		VARCHAR(100) NOT NULL,
 GRANTEE 		VARCHAR(100) NOT NULL,
 DESCRIPTION 	VARCHAR(255),
 PRIMARY KEY (FEATURE,RIGHTS,GRANTEE),
 FOREIGN KEY (FEATURE) REFERENCES FF4J_FEATURE(UID)
);

CREATE TABLE FF4J_FEATURE_STRAT ( 
 FEATURE 		VARCHAR(100) NOT NULL,
 CLASSNAME 		VARCHAR(200) NOT NULL,
 INITPARAMS 	VARCHAR(500),
 PRIMARY KEY (FEATURE,CLASSNAME),
 FOREIGN KEY (FEATURE) REFERENCES FF4J_FEATURE(UID)
);

CREATE TABLE FF4J_PROPERTY ( 
 UID 	VARCHAR(100) NOT NULL,
 CREATED 	DATETIME NOT NULL,
 LASTMODIFIED 	DATETIME NOT NULL,
 OWNER 	VARCHAR(100),
 DESCRIPTION 	VARCHAR(255),
 CLASSNAME 	VARCHAR(255) NOT NULL,
 READONLY 	INTEGER NOT NULL,
 VAL 	VARCHAR(255) NOT NULL,
 FIXEDVALUES 	VARCHAR(1000),
 STRAT_CLASS 	VARCHAR(1000) NOT NULL,
 STRAT_PARAMS 	VARCHAR(1000),
 PRIMARY KEY (UID)
);
CREATE TABLE FF4J_PROPERTY_PROP ( 
 UID 	VARCHAR(100) NOT NULL,
 CLASSNAME 	VARCHAR(255) NOT NULL,
 VAL 	VARCHAR(255) NOT NULL,
 FIXEDVALUES 	VARCHAR(1000),
 PROP_UID 	VARCHAR(100) NOT NULL,
 PRIMARY KEY (UID,PROP_UID),
 FOREIGN KEY (PROP_UID) REFERENCES FF4J_PROPERTY(UID)
);
CREATE TABLE FF4J_PROPERTY_PERM ( 
 PROPERTY 	VARCHAR(100) NOT NULL,
 RIGHTS 	VARCHAR(100) NOT NULL,
 GRANTEE 	VARCHAR(100) NOT NULL,
 DESCRIPTION 	VARCHAR(255),
 PRIMARY KEY (PROPERTY,RIGHTS,GRANTEE),
 FOREIGN KEY (PROPERTY) REFERENCES FF4J_PROPERTY(UID)
);

CREATE TABLE FF4J_AUDIT_TRAIL ( 
 UID 	VARCHAR(100) NOT NULL,
 CREATED 	DATETIME NOT NULL,
 LASTMODIFIED 	DATETIME NOT NULL,
 OWNER 	VARCHAR(100),
 DESCRIPTION 	VARCHAR(255),
 EVT_TIME 	TIMESTAMP NOT NULL,
 EVT_TYPE 	VARCHAR(30) NOT NULL,
 NAME 	VARCHAR(30) NOT NULL,
 ACTION 	VARCHAR(30) NOT NULL,
 HOSTNAME 	VARCHAR(100),
 SOURCE 	VARCHAR(100),
 DURATION 	INTEGER NOT NULL,
 EVT_VALUE 	VARCHAR(100) NOT NULL,
 EVT_KEYS 	VARCHAR(1000) NOT NULL,
 PRIMARY KEY (UID,EVT_TIME)
);
CREATE TABLE FF4J_FEATURE_USAGE ( 
 UID 	VARCHAR(100) NOT NULL,
 CREATED 	DATETIME NOT NULL,
 LASTMODIFIED 	DATETIME NOT NULL,
 OWNER 	VARCHAR(100),
 DESCRIPTION 	VARCHAR(255),
 EVT_TIME 	TIMESTAMP NOT NULL,
 EVT_TYPE 	VARCHAR(30) NOT NULL,
 NAME 	VARCHAR(30) NOT NULL,
 ACTION 	VARCHAR(30) NOT NULL,
 HOSTNAME 	VARCHAR(100),
 SOURCE 	VARCHAR(100),
 DURATION 	INTEGER NOT NULL,
 EVT_VALUE 	VARCHAR(100) NOT NULL,
 EVT_KEYS 	VARCHAR(1000) NOT NULL,
 PRIMARY KEY (UID,EVT_TIME)
);

CREATE TABLE FF4J_PERMISSION ( 
 TARGET 	VARCHAR(100) NOT NULL,
 RIGHTS 	VARCHAR(100) NOT NULL,
 GRANTEE 	VARCHAR(100) NOT NULL,
 GRANTEETYPE
 DESCRIPTION 	VARCHAR(255),
 PRIMARY KEY (RIGHTS,GRANTEE,TARGET)
);

CREATE TABLE FF4J_USER ( 
 UID 			VARCHAR(100) NOT NULL,
 CREATED 		DATETIME NOT NULL,
 LASTMODIFIED 	DATETIME NOT NULL,
 OWNER 			VARCHAR(100),
 DESCRIPTION 	VARCHAR(255),
 PASSWORD 		VARCHAR(255) NOT NULL,
 LASTNAME 		VARCHAR(100),
 FIRSTNAME 		VARCHAR(100),
 PRIMARY KEY (UID)
);
CREATE TABLE FF4J_ROLE ( 
 NAME 			VARCHAR(100) NOT NULL,
 DESCRIPTION 	VARCHAR(255),
 PRIMARY KEY (NAME)
);
CREATE TABLE FF4J_USER_ROLE_A ( 
 REF_USER 	VARCHAR(100) NOT NULL,
 REF_GROUP 	VARCHAR(100) NOT NULL,
 PRIMARY KEY (REF_USER,REF_GROUP),
 FOREIGN KEY (REF_USER) REFERENCES FF4J_USER(UID),
 FOREIGN KEY (REF_GROUP) REFERENCES FF4J_ROLE(NAME)
);

