/*
 * FF4J (ff4j.org) WebAPI
 * Administrate and operate all tasks on your features through this api.
 *
 * OpenAPI spec version: 1.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.ff4j.store.client.model;

/*
 * #%L
 * ff4j-core
 * %%
 * Copyright (C) 2013 - 2017 FF4J
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.ff4j.store.client.model.InlineResponse200EventRepositoryBarChart;
import org.ff4j.store.client.model.InlineResponse200EventRepositoryEventsPie;
import java.io.IOException;

/**
 * EventRepositoryApiBean
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-27T20:07:45.848Z")
public class EventRepositoryApiBean {
  @SerializedName("barChart")
  private InlineResponse200EventRepositoryBarChart barChart = null;

  @SerializedName("eventsPie")
  private InlineResponse200EventRepositoryEventsPie eventsPie = null;

  @SerializedName("hitCount")
  private Integer hitCount = null;

  @SerializedName("type")
  private String type = null;

  public EventRepositoryApiBean barChart(InlineResponse200EventRepositoryBarChart barChart) {
    this.barChart = barChart;
    return this;
  }

   /**
   * Get barChart
   * @return barChart
  **/
  @ApiModelProperty(value = "")
  public InlineResponse200EventRepositoryBarChart getBarChart() {
    return barChart;
  }

  public void setBarChart(InlineResponse200EventRepositoryBarChart barChart) {
    this.barChart = barChart;
  }

  public EventRepositoryApiBean eventsPie(InlineResponse200EventRepositoryEventsPie eventsPie) {
    this.eventsPie = eventsPie;
    return this;
  }

   /**
   * Get eventsPie
   * @return eventsPie
  **/
  @ApiModelProperty(value = "")
  public InlineResponse200EventRepositoryEventsPie getEventsPie() {
    return eventsPie;
  }

  public void setEventsPie(InlineResponse200EventRepositoryEventsPie eventsPie) {
    this.eventsPie = eventsPie;
  }

  public EventRepositoryApiBean hitCount(Integer hitCount) {
    this.hitCount = hitCount;
    return this;
  }

   /**
   * Get hitCount
   * @return hitCount
  **/
  @ApiModelProperty(value = "")
  public Integer getHitCount() {
    return hitCount;
  }

  public void setHitCount(Integer hitCount) {
    this.hitCount = hitCount;
  }

  public EventRepositoryApiBean type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventRepositoryApiBean eventRepositoryApiBean = (EventRepositoryApiBean) o;
    return Objects.equals(this.barChart, eventRepositoryApiBean.barChart) &&
        Objects.equals(this.eventsPie, eventRepositoryApiBean.eventsPie) &&
        Objects.equals(this.hitCount, eventRepositoryApiBean.hitCount) &&
        Objects.equals(this.type, eventRepositoryApiBean.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(barChart, eventsPie, hitCount, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventRepositoryApiBean {\n");
    
    sb.append("    barChart: ").append(toIndentedString(barChart)).append("\n");
    sb.append("    eventsPie: ").append(toIndentedString(eventsPie)).append("\n");
    sb.append("    hitCount: ").append(toIndentedString(hitCount)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

