/*
 * FF4J (ff4j.org) WebAPI
 * Administrate and operate all tasks on your features through this api.
 *
 * OpenAPI spec version: 1.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.ff4j.store.client.model;

/*
 * #%L
 * ff4j-core
 * %%
 * Copyright (C) 2013 - 2017 FF4J
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.ff4j.store.client.model.InlineResponse200FeaturesStoreCache;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * FeatureStoreApiBean
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-27T20:07:45.848Z")
public class FeatureStoreApiBean {
  @SerializedName("cache")
  private InlineResponse200FeaturesStoreCache cache = null;

  @SerializedName("features")
  private List<String> features = null;

  @SerializedName("groups")
  private List<String> groups = null;

  @SerializedName("numberOfFeatures")
  private Integer numberOfFeatures = null;

  @SerializedName("numberOfGroups")
  private Integer numberOfGroups = null;

  @SerializedName("type")
  private String type = null;

  public FeatureStoreApiBean cache(InlineResponse200FeaturesStoreCache cache) {
    this.cache = cache;
    return this;
  }

   /**
   * Get cache
   * @return cache
  **/
  @ApiModelProperty(value = "")
  public InlineResponse200FeaturesStoreCache getCache() {
    return cache;
  }

  public void setCache(InlineResponse200FeaturesStoreCache cache) {
    this.cache = cache;
  }

  public FeatureStoreApiBean features(List<String> features) {
    this.features = features;
    return this;
  }

  public FeatureStoreApiBean addFeaturesItem(String featuresItem) {
    if (this.features == null) {
      this.features = new ArrayList<String>();
    }
    this.features.add(featuresItem);
    return this;
  }

   /**
   * Get features
   * @return features
  **/
  @ApiModelProperty(value = "")
  public List<String> getFeatures() {
    return features;
  }

  public void setFeatures(List<String> features) {
    this.features = features;
  }

  public FeatureStoreApiBean groups(List<String> groups) {
    this.groups = groups;
    return this;
  }

  public FeatureStoreApiBean addGroupsItem(String groupsItem) {
    if (this.groups == null) {
      this.groups = new ArrayList<String>();
    }
    this.groups.add(groupsItem);
    return this;
  }

   /**
   * Get groups
   * @return groups
  **/
  @ApiModelProperty(value = "")
  public List<String> getGroups() {
    return groups;
  }

  public void setGroups(List<String> groups) {
    this.groups = groups;
  }

  public FeatureStoreApiBean numberOfFeatures(Integer numberOfFeatures) {
    this.numberOfFeatures = numberOfFeatures;
    return this;
  }

   /**
   * Get numberOfFeatures
   * @return numberOfFeatures
  **/
  @ApiModelProperty(value = "")
  public Integer getNumberOfFeatures() {
    return numberOfFeatures;
  }

  public void setNumberOfFeatures(Integer numberOfFeatures) {
    this.numberOfFeatures = numberOfFeatures;
  }

  public FeatureStoreApiBean numberOfGroups(Integer numberOfGroups) {
    this.numberOfGroups = numberOfGroups;
    return this;
  }

   /**
   * Get numberOfGroups
   * @return numberOfGroups
  **/
  @ApiModelProperty(value = "")
  public Integer getNumberOfGroups() {
    return numberOfGroups;
  }

  public void setNumberOfGroups(Integer numberOfGroups) {
    this.numberOfGroups = numberOfGroups;
  }

  public FeatureStoreApiBean type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeatureStoreApiBean featureStoreApiBean = (FeatureStoreApiBean) o;
    return Objects.equals(this.cache, featureStoreApiBean.cache) &&
        Objects.equals(this.features, featureStoreApiBean.features) &&
        Objects.equals(this.groups, featureStoreApiBean.groups) &&
        Objects.equals(this.numberOfFeatures, featureStoreApiBean.numberOfFeatures) &&
        Objects.equals(this.numberOfGroups, featureStoreApiBean.numberOfGroups) &&
        Objects.equals(this.type, featureStoreApiBean.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cache, features, groups, numberOfFeatures, numberOfGroups, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeatureStoreApiBean {\n");
    
    sb.append("    cache: ").append(toIndentedString(cache)).append("\n");
    sb.append("    features: ").append(toIndentedString(features)).append("\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("    numberOfFeatures: ").append(toIndentedString(numberOfFeatures)).append("\n");
    sb.append("    numberOfGroups: ").append(toIndentedString(numberOfGroups)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

