/*
 * FF4J (ff4j.org) WebAPI
 * Administrate and operate all tasks on your features through this api.
 *
 * OpenAPI spec version: 1.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.ff4j.store.client.model;

/*
 * #%L
 * ff4j-core
 * %%
 * Copyright (C) 2013 - 2017 FF4J
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.ff4j.store.client.model.InlineResponse2003;
import org.ff4j.store.client.model.InlineResponse2004FlippingStrategy;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * InlineResponse2004
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-27T20:07:45.848Z")
public class InlineResponse2004 {
  @SerializedName("customProperties")
  private Map<String, InlineResponse2003> customProperties = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("enable")
  private Boolean enable = null;

  @SerializedName("flippingStrategy")
  private InlineResponse2004FlippingStrategy flippingStrategy = null;

  @SerializedName("group")
  private String group = null;

  @SerializedName("permissions")
  private List<String> permissions = null;

  @SerializedName("uid")
  private String uid = null;

  public InlineResponse2004 customProperties(Map<String, InlineResponse2003> customProperties) {
    this.customProperties = customProperties;
    return this;
  }

  public InlineResponse2004 putCustomPropertiesItem(String key, InlineResponse2003 customPropertiesItem) {
    if (this.customProperties == null) {
      this.customProperties = new HashMap<String, InlineResponse2003>();
    }
    this.customProperties.put(key, customPropertiesItem);
    return this;
  }

   /**
   * Get customProperties
   * @return customProperties
  **/
  @ApiModelProperty(value = "")
  public Map<String, InlineResponse2003> getCustomProperties() {
    return customProperties;
  }

  public void setCustomProperties(Map<String, InlineResponse2003> customProperties) {
    this.customProperties = customProperties;
  }

  public InlineResponse2004 description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public InlineResponse2004 enable(Boolean enable) {
    this.enable = enable;
    return this;
  }

   /**
   * Get enable
   * @return enable
  **/
  @ApiModelProperty(value = "")
  public Boolean getEnable() {
    return enable;
  }

  public void setEnable(Boolean enable) {
    this.enable = enable;
  }

  public InlineResponse2004 flippingStrategy(InlineResponse2004FlippingStrategy flippingStrategy) {
    this.flippingStrategy = flippingStrategy;
    return this;
  }

   /**
   * Get flippingStrategy
   * @return flippingStrategy
  **/
  @ApiModelProperty(value = "")
  public InlineResponse2004FlippingStrategy getFlippingStrategy() {
    return flippingStrategy;
  }

  public void setFlippingStrategy(InlineResponse2004FlippingStrategy flippingStrategy) {
    this.flippingStrategy = flippingStrategy;
  }

  public InlineResponse2004 group(String group) {
    this.group = group;
    return this;
  }

   /**
   * Get group
   * @return group
  **/
  @ApiModelProperty(value = "")
  public String getGroup() {
    return group;
  }

  public void setGroup(String group) {
    this.group = group;
  }

  public InlineResponse2004 permissions(List<String> permissions) {
    this.permissions = permissions;
    return this;
  }

  public InlineResponse2004 addPermissionsItem(String permissionsItem) {
    if (this.permissions == null) {
      this.permissions = new ArrayList<String>();
    }
    this.permissions.add(permissionsItem);
    return this;
  }

   /**
   * Get permissions
   * @return permissions
  **/
  @ApiModelProperty(value = "")
  public List<String> getPermissions() {
    return permissions;
  }

  public void setPermissions(List<String> permissions) {
    this.permissions = permissions;
  }

  public InlineResponse2004 uid(String uid) {
    this.uid = uid;
    return this;
  }

   /**
   * Get uid
   * @return uid
  **/
  @ApiModelProperty(value = "")
  public String getUid() {
    return uid;
  }

  public void setUid(String uid) {
    this.uid = uid;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2004 inlineResponse2004 = (InlineResponse2004) o;
    return Objects.equals(this.customProperties, inlineResponse2004.customProperties) &&
        Objects.equals(this.description, inlineResponse2004.description) &&
        Objects.equals(this.enable, inlineResponse2004.enable) &&
        Objects.equals(this.flippingStrategy, inlineResponse2004.flippingStrategy) &&
        Objects.equals(this.group, inlineResponse2004.group) &&
        Objects.equals(this.permissions, inlineResponse2004.permissions) &&
        Objects.equals(this.uid, inlineResponse2004.uid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customProperties, description, enable, flippingStrategy, group, permissions, uid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2004 {\n");
    
    sb.append("    customProperties: ").append(toIndentedString(customProperties)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    enable: ").append(toIndentedString(enable)).append("\n");
    sb.append("    flippingStrategy: ").append(toIndentedString(flippingStrategy)).append("\n");
    sb.append("    group: ").append(toIndentedString(group)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

