/*
 * FF4J (ff4j.org) WebAPI
 * Administrate and operate all tasks on your features through this api.
 *
 * OpenAPI spec version: 1.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.ff4j.store.client.model;

/*
 * #%L
 * ff4j-core
 * %%
 * Copyright (C) 2013 - 2017 FF4J
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse200FeaturesStoreCache
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-27T20:07:45.848Z")
public class InlineResponse200FeaturesStoreCache {
  @SerializedName("cacheProvider")
  private String cacheProvider = null;

  @SerializedName("cacheStore")
  private String cacheStore = null;

  @SerializedName("featureNames")
  private List<String> featureNames = null;

  @SerializedName("propertyNames")
  private List<String> propertyNames = null;

  public InlineResponse200FeaturesStoreCache cacheProvider(String cacheProvider) {
    this.cacheProvider = cacheProvider;
    return this;
  }

   /**
   * Get cacheProvider
   * @return cacheProvider
  **/
  @ApiModelProperty(value = "")
  public String getCacheProvider() {
    return cacheProvider;
  }

  public void setCacheProvider(String cacheProvider) {
    this.cacheProvider = cacheProvider;
  }

  public InlineResponse200FeaturesStoreCache cacheStore(String cacheStore) {
    this.cacheStore = cacheStore;
    return this;
  }

   /**
   * Get cacheStore
   * @return cacheStore
  **/
  @ApiModelProperty(value = "")
  public String getCacheStore() {
    return cacheStore;
  }

  public void setCacheStore(String cacheStore) {
    this.cacheStore = cacheStore;
  }

  public InlineResponse200FeaturesStoreCache featureNames(List<String> featureNames) {
    this.featureNames = featureNames;
    return this;
  }

  public InlineResponse200FeaturesStoreCache addFeatureNamesItem(String featureNamesItem) {
    if (this.featureNames == null) {
      this.featureNames = new ArrayList<String>();
    }
    this.featureNames.add(featureNamesItem);
    return this;
  }

   /**
   * Get featureNames
   * @return featureNames
  **/
  @ApiModelProperty(value = "")
  public List<String> getFeatureNames() {
    return featureNames;
  }

  public void setFeatureNames(List<String> featureNames) {
    this.featureNames = featureNames;
  }

  public InlineResponse200FeaturesStoreCache propertyNames(List<String> propertyNames) {
    this.propertyNames = propertyNames;
    return this;
  }

  public InlineResponse200FeaturesStoreCache addPropertyNamesItem(String propertyNamesItem) {
    if (this.propertyNames == null) {
      this.propertyNames = new ArrayList<String>();
    }
    this.propertyNames.add(propertyNamesItem);
    return this;
  }

   /**
   * Get propertyNames
   * @return propertyNames
  **/
  @ApiModelProperty(value = "")
  public List<String> getPropertyNames() {
    return propertyNames;
  }

  public void setPropertyNames(List<String> propertyNames) {
    this.propertyNames = propertyNames;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200FeaturesStoreCache inlineResponse200FeaturesStoreCache = (InlineResponse200FeaturesStoreCache) o;
    return Objects.equals(this.cacheProvider, inlineResponse200FeaturesStoreCache.cacheProvider) &&
        Objects.equals(this.cacheStore, inlineResponse200FeaturesStoreCache.cacheStore) &&
        Objects.equals(this.featureNames, inlineResponse200FeaturesStoreCache.featureNames) &&
        Objects.equals(this.propertyNames, inlineResponse200FeaturesStoreCache.propertyNames);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cacheProvider, cacheStore, featureNames, propertyNames);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200FeaturesStoreCache {\n");
    
    sb.append("    cacheProvider: ").append(toIndentedString(cacheProvider)).append("\n");
    sb.append("    cacheStore: ").append(toIndentedString(cacheStore)).append("\n");
    sb.append("    featureNames: ").append(toIndentedString(featureNames)).append("\n");
    sb.append("    propertyNames: ").append(toIndentedString(propertyNames)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

