DROP TABLE FF4J_USER_ROLE_A;
DROP TABLE FF4J_USER_PERM;
DROP TABLE FF4J_USER;
DROP TABLE FF4J_ROLE_PERM;
DROP TABLE FF4J_ROLE;
DROP TABLE FF4J_FEATURE_STRAT_P;
DROP TABLE FF4J_FEATURE_STRAT;
DROP TABLE FF4J_FEATURE_PERM;
DROP TABLE FF4J_FEATURE_PROP;
DROP TABLE FF4J_FEATURE;
DROP TABLE FF4J_PROPERTY;
DROP TABLE FF4J_FEATURE_USAGE;
DROP TABLE FF4J_AUDIT_TRAIL;


