package org.ff4j.store;

/*
 * #%L ff4j-core %% Copyright (C) 2013 Ff4J %% Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS"
 * BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License. #L%
 */

/**
 * Specialization of a Feature store to add sql query.
 * 
 * @author <a href="mailto:cedrick.lunven@gmail.com">Cedrick LUNVEN</a>
 */
public interface JdbcFeatureStoreConstants {

	 /** sql query expression */
    String SQLQUERY_GET_FEATURE_BY_ID = "SELECT FEATURE_NAME,FEATURE_STATUS,DESCRIPTION,STRATEGY,EXPRESSION,GROUPNAME,REGION_IDENTIFIER FROM FF4J_FEATURES WHERE FEATURE_NAME = ?";

    /** sql query expression */
    String SQLQUERY_ALLFEATURES = "SELECT FEATURE_NAME,FEATURE_STATUS,DESCRIPTION,STRATEGY,EXPRESSION,GROUPNAME,REGION_IDENTIFIER FROM FF4J_FEATURES";

    /** sql query expression */
    String SQLQUERY_ALLGROUPS = "SELECT DISTINCT(GROUPNAME) FROM FF4J_FEATURES";

    /** sql query expression */
    String SQLQUERY_GET_FEATURE_GROUP = "SELECT FEATURE_NAME,FEATURE_STATUS,DESCRIPTION,STRATEGY,EXPRESSION,GROUPNAME,REGION_IDENTIFIER FROM FF4J_FEATURES WHERE GROUPNAME = ?";

    /** sql query expression */
    String SQL_DISABLE_BY_GROUP_REGION = "UPDATE FF4J_FEATURES SET FEATURE_STATUS = 0 WHERE FEATURE_NAME = ? AND GROUPNAME=? AND REGION_IDENTIFIER=?";
   
    /** sql query expression */
    String SQL_EXIST = "SELECT COUNT(FEATURE_NAME) FROM FF4J_FEATURES WHERE FEATURE_NAME = ?";

    /** sql query expression */
    String SQL_DISABLE = "UPDATE FF4J_FEATURES SET FEATURE_STATUS = 0 WHERE FEATURE_NAME = ?";

    /** sql query expression */
    String SQL_ADD_TO_GROUP = "UPDATE FF4J_FEATURES SET GROUPNAME = ? WHERE FEATURE_NAME = ?";

    /** sql query expression */
    String SQL_REMOVE_FROM_GROUP = "UPDATE FF4J_FEATURES SET GROUPNAME = NULL WHERE FEATURE_NAME = ?";

    /** sql query expression */
    String SQL_ENABLE = "UPDATE FF4J_FEATURES SET FEATURE_STATUS = 1 WHERE FEATURE_NAME = ?";

    /** sql query expression */
    String SQL_ENABLE_BY_GROUP_REGION = "UPDATE FF4J_FEATURES SET FEATURE_STATUS = 1 WHERE FEATURE_NAME = ? AND GROUPNAME=? AND REGION_IDENTIFIER=?";

    /** sql query expression */
    String SQL_ENABLE_GROUP = "UPDATE FF4J_FEATURES SET FEATURE_STATUS = 1 WHERE GROUPNAME = ?";

    /** sql query expression */
    String SQL_DISABLE_GROUP = "UPDATE FF4J_FEATURES SET FEATURE_STATUS = 0 WHERE GROUPNAME = ?";

    /** sql query expression */
    String SQL_EXIST_GROUP = "SELECT COUNT(*) FROM FF4J_FEATURES WHERE GROUPNAME = ?";

    /** sql query expression */
    String SQL_CREATE = "INSERT INTO FF4J_FEATURES(FEATURE_NAME, FEATURE_STATUS, DESCRIPTION, STRATEGY,EXPRESSION, GROUPNAME,REGION_IDENTIFIER) VALUES(?, ?, ?, ?, ?, ?,?)";

	/** sql query expression */
	String SQLQUERY_ALLFEATURES_BY_GROUP_REGION = "SELECT FEATURE_NAME,FEATURE_STATUS,DESCRIPTION,STRATEGY,EXPRESSION,GROUPNAME,REGION_IDENTIFIER FROM FF4J_FEATURES WHERE GROUPNAME=? AND REGION_IDENTIFIER=?";

	/** sql query expression */
	String SQLQUERY_ALLFEATURES_BY_REGION = "SELECT FEATURE_NAME,FEATURE_STATUS,DESCRIPTION,STRATEGY,EXPRESSION,GROUPNAME,REGION_IDENTIFIER FROM FF4J_FEATURES WHERE REGION_IDENTIFIER=?";
	
	/** sql query expression */
	String SQL_EXIST_FOR_GROUP_REGION = "SELECT COUNT(FEATURE_NAME) FROM FF4J_FEATURES WHERE FEATURE_NAME = ? AND GROUPNAME=? AND REGION_IDENTIFIER=?";
    
    /** sql query expression */
    String SQL_DELETE = "DELETE FROM FF4J_FEATURES WHERE FEATURE_NAME = ?";

    /** sql query expression */
	String SQL_FEATURE_STATUS_ENABLE  = "UPDATE FF4J_FEATURES SET FEATURE_STATUS  = 1 WHERE FEATURE_NAME = ? AND GROUPNAME=? AND REGION_IDENTIFIER=?";

	/** sql query expression */
	String SQL_FEATURE_STATUS_DISABLE = "UPDATE FF4J_FEATURES SET FEATURE_STATUS = 0 WHERE FEATURE_NAME = ? AND GROUPNAME=? AND REGION_IDENTIFIER=?";

	/** sql query expression */
	String SQL_DELETE_BY_GROUP_REGION  = "DELETE FROM FF4J_FEATURES WHERE FEATURE_NAME = ? AND GROUPNAME=? AND REGION_IDENTIFIER=?";

	/** sql query expression */
	String SQLQUERY_GET_FEATURE_BY_GROUP_REGION = "SELECT FEATURE_NAME,FEATURE_STATUS,DESCRIPTION,STRATEGY,EXPRESSION,GROUPNAME,REGION_IDENTIFIER FROM FF4J_FEATURES WHERE FEATURE_NAME = ? AND GROUPNAME=? AND REGION_IDENTIFIER=?";

    /** sql query expression */
    String SQL_UPDATE = "UPDATE FF4J_FEATURES SET FEATURE_STATUS=?,DESCRIPTION=?,STRATEGY=?,EXPRESSION=?,GROUPNAME=? WHERE FEATURE_NAME = ?";

    /** sql query expression */
	String SQL_UPDATE_BY_GROUP_REGION = "UPDATE FF4J_FEATURES SET FEATURE_STATUS =?,DESCRIPTION=?,STRATEGY=?,EXPRESSION=?,GROUPNAME=?,REGION_IDENTIFIER=? WHERE FEATURE_NAME = ? AND GROUPNAME=? AND REGION_IDENTIFIER=?";

    /** sql query expression */
    String SQL_ADD_ROLE = "INSERT INTO FF4J_ROLES(FEATURE_NAME, ROLE_NAME) VALUES (?,?)";
    
	/** sql query expression */
	String SQL_ADD_ROLE_BY_GROUP_REGION = "INSERT INTO FF4J_ROLES(FEATURE_NAME, ROLE_NAME,GROUPNAME,REGION_IDENTIFIER) VALUES (?,?,?,?)";

	/** sql query expression */
	String SQL_DELETE_ROLE_BY_GROUP_REGION = "DELETE FROM FF4J_ROLES WHERE FEATURE_NAME = ? AND ROLE_NAME = ? AND GROUPNAME = ? AND REGION_IDENTIFIER=?";

	/** sql query expression */
	String SQL_GET_ROLES_BY_GROUP_REGION = "SELECT ROLE_NAME FROM FF4J_ROLES WHERE FEATURE_NAME = ? AND GROUPNAME=? AND REGION_IDENTIFIER=?";

	/** sql query expression */
	String SQL_GET_ALLROLES_BY_GROUP_REGION = "SELECT FEATURE_NAME,ROLE_NAME,GROUPNAME,REGION_IDENTIFIER FROM FF4J_ROLES WHERE GROUPNAME=? AND REGION_IDENTIFIER=?";

	/** sql query expression */
	String SQL_GET_ALLROLES_GROUP_REGION = "SELECT FEATURE_NAME,ROLE_NAME,GROUPNAME,REGION_IDENTIFIER FROM FF4J_ROLES WHERE GROUPNAME=? AND REGION_IDENTIFIER=?";

	/** sql query expression */
	String SQL_GET_ALLROLES_BY_REGION = "SELECT FEATURE_NAME,ROLE_NAME,GROUPNAME,REGION_IDENTIFIER FROM FF4J_ROLES WHERE REGION_IDENTIFIER=?";

	/** sql query expression */
	String SQL_GET_ALLGROUPS_BY_REGION = "SELECT DISTINCT GROUPNAME FROM FF4J_FEATURES WHERE REGION_IDENTIFIER=?";

	

    /** sql query expression */
    String SQL_DELETE_ROLE = "DELETE FROM FF4J_ROLES WHERE FEATURE_NAME = ? AND ROLE_NAME = ?";

    /** sql query expression */
    String SQL_GET_ROLES = "SELECT ROLE_NAME FROM FF4J_ROLES WHERE FEATURE_NAME = ?";

    /** sql query expression */
    String SQL_GET_ALLROLES = "SELECT FEATURE_NAME,ROLE_NAME FROM FF4J_ROLES";

    /** sql column name from table FF4J_FEATURES. */
    String COL_FEAT_UID = "FEATURE_NAME";

    /** sql column name from table FF4J_FEATURES. */
    String COL_FEAT_ENABLE = "FEATURE_STATUS";

    /** sql column name from table FF4J_FEATURES. */
    String COL_FEAT_DESCRIPTION = "DESCRIPTION";

    /** sql column name from table FF4J_FEATURES. */
	String COL_FEAT_REGION_IDENTIFIER = "REGION_IDENTIFIER";
	
    /** sql column name from table FF4J_FEATURES. */
    String COL_FEAT_GROUPNAME = "GROUPNAME";

    /** sql column name from table FF4J_FEATURES. */
    String COL_FEAT_STRATEGY = "STRATEGY";

    /** sql column name from table FF4J_FEATURES. */
    String COL_FEAT_EXPRESSION = "EXPRESSION";

    /** sql column name from table FF4J_ROLES. */
    String COL_ROLE_FEATID = "FEATURE_NAME";

    /** sql column name from table FF4J_ROLES. */
    String COL_ROLE_ROLENAME = "ROLE_NAME";

}