CREATE TABLE FLIP_POINT (
  UID     		VARCHAR(50),
  ENABLE  		INTEGER NOT NULL,
  DESCRIPTION 	VARCHAR(255),
  STRATEGY		VARCHAR(255),
  PRIMARY KEY(UID)
);

CREATE TABLE FLIP_POINT_ROLE (
  FPOINT_UID   VARCHAR(50) REFERENCES FLIP_POINT(UID),
  ROLE_NAME    VARCHAR(50),
  PRIMARY KEY(FPOINT_UID, ROLE_NAME)
);